version: '3'
services:
  web:
    image: php:8.2-apache
    container_name: php-web
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: >
      bash -c "apt-get update && apt-get install -y default-mysql-client &&
               docker-php-ext-install mysqli pdo pdo_mysql &&
               apache2-foreground"
   # networks:
    #  - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_DATABASE: mydb
    #networks:
     # - app-network

#networks:
 # app-network:
  #  driver: bridge